# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-TrackIT
version:      0.01
version_from: lib/Net/TrackIT.pm
installdirs:  site
requires:
    HTTP::Request:                 0
    LWP::UserAgent:                0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
